name: sast-dependency-check

on:
  workflow_call:

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "repo-sast"
          format: "HTML"
          args: "--failOnCVSS 6.5"